# Generated by Django 5.2.1 on 2025-05-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studnet_id',
            new_name='student_id',
        ),
    ]
