# Generated by Django 5.1.7 on 2025-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_studnet_id_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
